apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-saleor-api'
  labels:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-api'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: '{{.Release.Name}}-saleor'
      service: '{{.Release.Name}}-saleor-api'
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-saleor'
        service: '{{.Release.Name}}-saleor-api'
    spec:
      restartPolicy: Always
      containers:
        - image: hnminh/saleor-api:kms
          name: saleor-api
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    '/bin/sh',
                    '-c',
                    'python3 manage.py migrate && python3 manage.py collectstatic --noinput && python3 manage.py populatedb && python3 manage.py createsuperuser --no-input --email=admin@kms-technology.com || true && python3 manage.py createsuperuser --no-input --email=minhhoang@kms-technology.com || true && echo "UPDATE public.warehouse_stock SET quantity = 2147483647" | python3 manage.py dbshell && sleep 30',
                  ]
          ports:
            - containerPort: 8000
              name: api
          env:
            - name: ENABLE_DEBUG_TOOLBAR
              value: 'True'
            - name: DEBUG
              value: 'True'
            - name: DATABASE_URL
              value: '{{ .Values.databaseUrl }}'
            - name: CACHE_URL
              value: '{{ .Values.redisUrl }}'
            - name: ALLOWED_CLIENT_HOSTS
              value: '{{ .Values.allowHosts }}, {{.Release.Name}}-saleor-dashboard, {{.Release.Name}}-saleor-storefront'
            - name: ALLOWED_HOSTS
              value: '{{ .Values.allowHosts }}, {{.Release.Name}}-saleor-dashboard, {{.Release.Name}}-saleor-storefront'
            - name: SECRET_KEY
              value: '{{ .Values.secretKey }}'
            - name: DJANGO_SUPERUSER_PASSWORD
              value: '{{ .Values.superUserPassword }}'
            - name: DASHBOARD_URL
              value: 'http://{{ .Values.dashboardIngress }}'
            - name: STOREFRONT_URL
              value: 'http://{{ .Values.storefrontIngress }}'
          resources:
            limits:
              cpu: '250m'
              memory: '250Mi'
            requests:
              cpu: '250m'
              memory: '250Mi'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-saleor-dashboard'
  labels:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-dashboard'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '{{.Release.Name}}-saleor'
      service: '{{.Release.Name}}-saleor-dashboard'
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-saleor'
        service: '{{.Release.Name}}-saleor-dashboard'
    spec:
      restartPolicy: Always
      containers:
        - image: hnminh/saleor-dashboard:kms
          name: saleor-dashboard
          imagePullPolicy: Always
          # Image with debug mode need to config webpack-dev-server port
          # command: ['/bin/sh']
          # args: ['-c', 'npm start -- --port 80 --host 0.0.0.0 --disable-host-check']
          ports:
            - containerPort: 80
              name: dashboard
          env:
            - name: DANGEROUSLY_DISABLE_HOST_CHECK
              value: 'true'
            - name: API_URI
              value: 'http://{{ .Values.apiIngress }}/graphql/'
          resources:
            limits:
              cpu: '150m'
              memory: '150Mi'
            requests:
              cpu: '150m'
              memory: '150Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-saleor-storefront'
  labels:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-storefront'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '{{.Release.Name}}-saleor'
      service: '{{.Release.Name}}-saleor-storefront'
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-saleor'
        service: '{{.Release.Name}}-saleor-storefront'
    spec:
      restartPolicy: Always
      containers:
        - image: hnminh/saleor-storefront:kms
          name: saleor-storefront
          imagePullPolicy: Always
          # Image with debug mode need to config webpack-dev-server port
          # command: ['/bin/sh']
          # args: ['-c', 'npm start -- --port 80 --host 0.0.0.0 --disable-host-check']
          ports:
            - containerPort: 80
              name: storefront
          env:
            - name: DANGEROUSLY_DISABLE_HOST_CHECK
              value: 'true'
            - name: API_URI
              value: 'http://{{ .Values.apiIngress }}/graphql/'
          resources:
            limits:
              cpu: '150m'
              memory: '150Mi'
            requests:
              cpu: '150m'
              memory: '150Mi'
